#!/usr/bin/env python3
# this file is the login front end
# it relays messages between the user and the greeter server

import sys
import getpass

from pydbus import SystemBus  # TODO: replace this. it's abandoned
from gi.repository import GLib


class LoggerInner(object):
    greeter_server_dbus_address = "com.greyltc.cgreet"

    def __init__(self, *args, **kwargs):
        self.greeter_server_dbus_path = '/' + self.greeter_server_dbus_address.replace('.','/')

        # connect to the system dbus
        self.system_bus = SystemBus()

        # create the main loop object
        self.loop = GLib.MainLoop.new(None, False)

        # subscribe to the server's signals
        self.system_bus.subscribe(object = self.greeter_server_dbus_path, signal_fired = self.prompt_action)

        # connect to the server
        self.server = self.system_bus.get(self.greeter_server_dbus_address)

    def prompt_action(self, name, path, interface, signal, data):
        if signal == 'prompt_text':
            prompt = data[0]
            if "assword" in prompt:
                response = getpass.getpass(prompt)
            else:
                response = input(prompt)
            self.server.respond(response)
        elif signal == "auth_complete":
            success = data[0]
            if success == True:
                print("Authentication successful!")
            else:
                print("Authentication failed!")
            
            # quit the main loop
            self.loop.quit()
    
    def run(self):
        # start the authentication routine
        self.server.authenticate()

        # run the main loop
        self.loop.run()


if __name__=="__main__":
    li = LoggerInner(sys.argv)
    li.run()